const KEY = {
  SUBJECT_CATEGORY_CONTROLLER: "SUBJECT_CATEGORY_CONTROLLER",
  TEACHER_CONTROLLER: "TEACHER_CONTROLLER",
  CURRICULUM_CONTROLLER: "CURRICULUM_CONTROLLER",
  STUDENT_CONTROLLER: "STUDENT_CONTROLLER",
  COURSE_CONTROLLER: "COURSE_CONTROLLER",
  COURSE_ACCOUNT_MAPPING_CONTROLLER: "COURSE_ACCOUNT_MAPPING_CONTROLLER",
  CLASS_CONTROLLER: "CLASS_CONTROLLER",
  SUBJECT_CLASS_MAPPING_CONTROLLER: "SUBJECT_CLASS_MAPPING_CONTROLLER",
  ACCOUNT_CONTROLLER: "ACCOUNT_CONTROLLER",
  DIVISION_CONTROLLER: "DIVISION_CONTROLLER",
  DEPARTMENT_OF_EDUCATION_CONTROLLERL: "DEPARTMENT_OF_EDUCATION_CONTROLLER",
  SCHOOL_CONTROLLER: "SCHOOL_CONTROLLER"
}

export default KEY
