export { default as Table } from "./Table"
export { default as Pagination } from "./Pagination"
export { default as TitlePage } from "./TitlePage"
export { default as DropdownSize } from "./DropdownSize"
export { default as useStore } from "./Context"
export { default as FooterModal } from "./FooterModal"
