const key = {
  SET_AUTH: "SET_AUTH",
  LOG_OUT: "LOG_OUT",
  SET_CONFIG_TYPE: "SET_CONFIG_TYPE",
  SET_CONFIG_AGE: "SET_CONFIG_AGE",
  SET_CONFIG_CATEGORY: "SET_CONFIG_CATEGORY",
  CALLING: "CALLING"
}

export default key
